'use client';

import { useState, useEffect, useRef } from 'react';
import { DEALER_CONFIG } from '../config/dealer';

interface Message {
  id: string;
  text: string;
  sender: 'user' | 'agent';
  timestamp: Date;
  actionType?: string;
  actions?: ActionButton[];
}

interface ActionButton {
  label: string;
  action: string;
  type: 'primary' | 'secondary';
}

export default function AIAgent() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      text: `Hello! 👋 I'm your DAKIRO Admin Assistant. As admin, you can:\n\n✓ Add devices to inventory\n✓ Manage agent allocations & stock\n✓ View customer & sales data\n✓ View payment reports\n✓ Monitor agent performance\n✓ Generate admin reports\n\nSales agents handle:\n• Customer registration\n• Creating sales\n• Recording payments\n• Generating receipts\n\nWhat would you like to do?`,
      sender: 'agent',
      timestamp: new Date(),
    },
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [showQuickForm, setShowQuickForm] = useState<string | null>(null);
  const [formData, setFormData] = useState<Record<string, string>>({});
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const parseCommand = (input: string) => {
    const lowerInput = input.toLowerCase();

    // Customer commands
    if (lowerInput.includes('add customer') || lowerInput.includes('new customer')) {
      return {
        type: 'ADD_CUSTOMER',
        description: 'Add Customer',
      };
    }

    // Device commands
    if (lowerInput.includes('add device') || lowerInput.includes('add phone')) {
      return {
        type: 'ADD_DEVICE',
        description: 'Add Device',
      };
    }

    // Search commands
    if (lowerInput.includes('search') || lowerInput.includes('find')) {
      return {
        type: 'SEARCH',
        description: 'Search Database',
      };
    }

    // Sale commands
    if (lowerInput.includes('create sale') || lowerInput.includes('new sale')) {
      return {
        type: 'CREATE_SALE',
        description: 'Create Sale',
      };
    }

    // Receipt commands
    if (lowerInput.includes('receipt') || lowerInput.includes('print')) {
      return {
        type: 'RECEIPT',
        description: 'Generate Receipt',
      };
    }

    // Payment commands
    if (lowerInput.includes('payment') || lowerInput.includes('pay')) {
      return {
        type: 'LOG_PAYMENT',
        description: 'Log Payment',
      };
    }

    // Help commands
    if (lowerInput.includes('help') || lowerInput.includes('what can you')) {
      return {
        type: 'HELP',
        description: 'Show Help',
      };
    }

    // Info commands
    if (lowerInput.includes('info') || lowerInput.includes('about')) {
      return {
        type: 'INFO',
        description: 'Show Info',
      };
    }

    return {
      type: 'QUESTION',
      description: 'Answer Question',
    };
  };

  const getAgentResponse = (commandType: string): { text: string; actions?: ActionButton[] } => {
    const responses: Record<string, { text: string; actions?: ActionButton[] }> = {
      ADD_CUSTOMER: {
        text: `⚠️ Customers are managed by sales agents only. Agents register customers when creating sales. As an admin, you can view all registered customers in the Customers section.`,
        actions: [
          { label: '📋 View Customers', action: 'VIEW_CUSTOMERS', type: 'primary' },
          { label: '📊 View Reports', action: 'VIEW_REPORTS', type: 'secondary' },
        ],
      },

      ADD_DEVICE: {
        text: `I'll help you add a phone device to inventory. Click the button below to open the form.`,
        actions: [
          { label: '📱 Add Device', action: 'SHOW_ADD_DEVICE_FORM', type: 'primary' },
          { label: '📦 View Inventory', action: 'VIEW_INVENTORY', type: 'secondary' },
        ],
      },

      CREATE_SALE: {
        text: `⚠️ Sales are created by agents only. Agents create sales records when customers purchase phones. As admin, you can view all sales in the Sales Analytics section.`,
        actions: [
          { label: '📊 View Sales', action: 'VIEW_SALES', type: 'primary' },
          { label: '📈 View Analytics', action: 'VIEW_ANALYTICS', type: 'secondary' },
        ],
      },

      LOG_PAYMENT: {
        text: `⚠️ Payments are logged by agents only. Agents record customer payments during transactions. As admin, you can view payment history in the reports section.`,
        actions: [
          { label: '📋 View Payments', action: 'VIEW_PAYMENTS', type: 'primary' },
          { label: '📊 Payment Reports', action: 'VIEW_PAYMENT_REPORTS', type: 'secondary' },
        ],
      },

      RECEIPT: {
        text: `⚠️ Receipts are generated by agents only. Agents create customer receipts during sales transactions. As admin, you can view sold phones and transaction history in reports.`,
        actions: [
          { label: '🖨️ View Sold Phones', action: 'VIEW_SOLD_PHONES', type: 'primary' },
          { label: '📊 View Reports', action: 'VIEW_REPORTS', type: 'secondary' },
        ],
      },

      SEARCH: {
        text: `I can search DAKIRO's database. What would you like to search for? Type your search term or click a button below.`,
        actions: [
          { label: '👥 Search Customers', action: 'SEARCH_CUSTOMERS', type: 'secondary' },
          { label: '📱 Search Devices', action: 'SEARCH_DEVICES', type: 'secondary' },
        ],
      },

      HELP: {
        text: `I'm DAKIRO's Admin Assistant. Here's what you can do:\n\n📱 **Inventory**: Add devices to stock\n👥 **View Data**: Customer profiles, agent performance\n📊 **Reports**: View sales, payments, analytics\n👨‍💼 **Agents**: Manage agent allocations and stock\n\n⚠️ **Agent-Only Operations** (handled by sales agents):\n• Register customers\n• Create sales records\n• Log customer payments\n• Generate receipts\n\nYour role: Manage inventory & agents, monitor performance.`,
      },

      INFO: {
        text: `Welcome to DAKIRO GENERAL ELECTRONICS!\n\n${DEALER_CONFIG.name}\nP.O BOX ${DEALER_CONFIG.poBox}, ${DEALER_CONFIG.location}\nTel: ${DEALER_CONFIG.phone}\n${DEALER_CONFIG.address}\n\nWe deal in: ${DEALER_CONFIG.dealersIn.join(', ')}\n\nI'm here to help manage your business efficiently!`,
      },

      QUESTION: {
        text: `I appreciate your question! While I'm primarily designed to help with business tasks, I'm always learning. For complex questions about DAKIRO's operations, feel free to ask the team or explore the relevant section in the app.\n\nIs there a specific task I can help you with?`,
      },
    };

    return responses[commandType] || responses.QUESTION;
  };

  const handleActionClick = (action: string) => {
    const actionHandlers: Record<string, () => void> = {
      'SHOW_ADD_DEVICE_FORM': () => {
        addMessage('Opening device form...', 'user');
        setShowQuickForm('ADD_DEVICE');
      },
      'VIEW_CUSTOMERS': () => {
        addMessage('🔄 Navigating to Customers section...', 'agent');
      },
      'VIEW_INVENTORY': () => {
        addMessage('🔄 Navigating to Phone Inventory...', 'agent');
      },
      'VIEW_SALES': () => {
        addMessage('🔄 Navigating to Sales...', 'agent');
      },
      'VIEW_PAYMENTS': () => {
        addMessage('🔄 Navigating to Payments...', 'agent');
      },
      'SEARCH_CUSTOMERS': () => {
        addMessage('Search by customer name or phone...', 'agent');
        setShowQuickForm('SEARCH_CUSTOMER');
      },
      'SEARCH_DEVICES': () => {
        addMessage('Search by IMEI or model name...', 'agent');
        setShowQuickForm('SEARCH_DEVICE');
      },
    };

    const handler = actionHandlers[action];
    if (handler) {
      handler();
    }
  };

  const addMessage = (text: string, sender: 'user' | 'agent') => {
    const newMessage: Message = {
      id: Date.now().toString(),
      text,
      sender,
      timestamp: new Date(),
    };
    setMessages((prev) => [...prev, newMessage]);
  };

  const handleSendMessage = async () => {
    if (!inputValue.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      text: inputValue,
      sender: 'user',
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInputValue('');
    setIsProcessing(true);

    // Simulate processing time
    setTimeout(() => {
      const command = parseCommand(inputValue);
      const response = getAgentResponse(command.type);
      const agentResponse: Message = {
        id: (Date.now() + 1).toString(),
        text: response.text,
        sender: 'agent',
        timestamp: new Date(),
        actionType: command.type,
        actions: response.actions,
      };

      setMessages((prev) => [...prev, agentResponse]);
      setIsProcessing(false);
    }, 1000);
  };

  const quickCommands = [
    { label: '📱 Add Device', cmd: 'add device' },
    { label: '👥 Manage Agents', cmd: 'manage agents' },
    { label: '📊 View Reports', cmd: 'view reports' },
    { label: '💼 View Sales', cmd: 'view sales' },
    { label: '📋 View Customers', cmd: 'view customers' },
    { label: '❓ Help', cmd: 'help' },
    { label: 'ℹ️ Info', cmd: 'about dakiro' },
  ];

  return (
    <>
      {/* Agent Button */}
      {!isOpen && (
        <button
          onClick={() => setIsOpen(true)}
          className="fixed bottom-6 right-6 bg-gradient-to-br from-primary to-primary/80 text-white rounded-full p-4 shadow-lg hover:shadow-xl transition-all hover:scale-110 z-40 flex items-center justify-center"
          title="Open AI Assistant"
        >
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M13 10V3L4 14h7v7l9-11h-7z"
            />
          </svg>
        </button>
      )}

      {/* Agent Window */}
      {isOpen && (
        <div className="fixed bottom-6 right-6 w-96 bg-white rounded-lg shadow-2xl z-50 flex flex-col h-[600px] border border-gray-200">
          {/* Header */}
          <div className="bg-gradient-to-r from-primary to-primary/80 text-white p-4 rounded-t-lg flex items-center justify-between">
            <div>
              <h3 className="font-bold text-lg">🤖 DAKIRO Assistant</h3>
              <p className="text-xs opacity-90">AI-powered task helper</p>
            </div>
            <button
              onClick={() => setIsOpen(false)}
              className="text-white hover:bg-white/20 rounded p-1 transition"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Messages */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-gray-50">
            {messages.map((msg) => (
              <div key={msg.id} className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div
                  className={`max-w-xs px-4 py-2 rounded-lg whitespace-pre-wrap text-sm ${
                    msg.sender === 'user'
                      ? 'bg-primary text-white rounded-br-none'
                      : 'bg-gray-200 text-gray-900 rounded-bl-none'
                  }`}
                >
                  <div>{msg.text}</div>
                  {msg.actions && msg.actions.length > 0 && (
                    <div className="mt-3 flex flex-col gap-2">
                      {msg.actions.map((btn, idx) => (
                        <button
                          key={idx}
                          onClick={() => handleActionClick(btn.action)}
                          className={`w-full px-3 py-2 rounded text-xs font-medium transition ${
                            btn.type === 'primary'
                              ? 'bg-primary hover:bg-primary/90 text-white'
                              : 'bg-white hover:bg-gray-100 text-primary border border-primary'
                          }`}
                        >
                          {btn.label}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ))}

            {isProcessing && (
              <div className="flex justify-start">
                <div className="bg-gray-200 text-gray-900 px-4 py-2 rounded-lg rounded-bl-none">
                  <div className="flex space-x-2">
                    <div className="w-2 h-2 bg-gray-600 rounded-full animate-bounce"></div>
                    <div className="w-2 h-2 bg-gray-600 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                    <div className="w-2 h-2 bg-gray-600 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                  </div>
                </div>
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {/* Quick Commands */}
          {messages.length <= 2 && (
            <div className="px-4 py-3 border-t border-gray-200 space-y-2 max-h-32 overflow-y-auto">
              <p className="text-xs text-gray-600 font-medium">Quick Commands:</p>
              <div className="grid grid-cols-2 gap-1">
                {quickCommands.map((cmd) => (
                  <button
                    key={cmd.label}
                    onClick={() => {
                      setInputValue(cmd.cmd);
                      setTimeout(() => {
                        const event = new KeyboardEvent('keydown', { key: 'Enter' });
                        document.dispatchEvent(event);
                      }, 100);
                    }}
                    className="text-xs bg-gray-100 hover:bg-primary/10 text-gray-700 hover:text-primary px-2 py-1 rounded transition border border-gray-200"
                  >
                    {cmd.label}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Input Area */}
          <div className="border-t border-gray-200 p-4 bg-white rounded-b-lg">
            <div className="flex gap-2">
              <input
                type="text"
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
                placeholder="Ask me to help..."
                className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary text-sm"
              />
              <button
                onClick={handleSendMessage}
                disabled={isProcessing || !inputValue.trim()}
                className="bg-primary hover:bg-primary/90 text-white px-4 py-2 rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                </svg>
              </button>
            </div>
          </div>

        {/* Quick Forms Modal */}
        {showQuickForm && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg shadow-xl max-w-md w-full mx-4 p-6">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-semibold text-gray-900">
                  {showQuickForm === 'ADD_DEVICE' && '📱 Add Device'}
                  {showQuickForm === 'SEARCH_CUSTOMER' && '🔍 Search Customer'}
                  {showQuickForm === 'SEARCH_DEVICE' && '🔍 Search Device'}
                </h3>
                <button
                  onClick={() => {
                    setShowQuickForm(null);
                    setFormData({});
                  }}
                  className="text-gray-500 hover:text-gray-700"
                >
                  ✕
                </button>
              </div>

              <div className="space-y-3">
                {showQuickForm === 'ADD_DEVICE' && (
                  <>
                    <input
                      type="text"
                      placeholder="Phone Model (e.g., Samsung A05)"
                      value={formData.model || ''}
                      onChange={(e) => setFormData({ ...formData, model: e.target.value })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary text-sm"
                    />
                    <input
                      type="text"
                      placeholder="IMEI (15 digits)"
                      value={formData.imei || ''}
                      onChange={(e) => setFormData({ ...formData, imei: e.target.value })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary text-sm"
                    />
                    <input
                      type="text"
                      placeholder="Serial Number"
                      value={formData.serial || ''}
                      onChange={(e) => setFormData({ ...formData, serial: e.target.value })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary text-sm"
                    />
                    <select
                      value={formData.condition || ''}
                      onChange={(e) => setFormData({ ...formData, condition: e.target.value })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary text-sm"
                    >
                      <option value="">Select Condition</option>
                      <option value="new">New</option>
                      <option value="refurbished">Refurbished</option>
                      <option value="used">Used</option>
                    </select>
                  </>
                )}

                {(showQuickForm === 'SEARCH_CUSTOMER' || showQuickForm === 'SEARCH_DEVICE') && (
                  <input
                    type="text"
                    placeholder={showQuickForm === 'SEARCH_CUSTOMER' ? 'Name or phone number' : 'IMEI or model name'}
                    value={formData.query || ''}
                    onChange={(e) => setFormData({ ...formData, query: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary text-sm"
                  />
                )}
              </div>

              <div className="flex gap-2 mt-4">
                <button
                  onClick={() => {
                    if (Object.values(formData).some((v) => v)) {
                      addMessage(
                        `✅ ${showQuickForm} completed!\n${JSON.stringify(formData, null, 2)}`,
                        'agent'
                      );
                      setShowQuickForm(null);
                      setFormData({});
                    }
                  }}
                  className="flex-1 px-3 py-2 bg-primary hover:bg-primary/90 text-white rounded-lg transition font-medium text-sm"
                >
                  Submit
                </button>
                <button
                  onClick={() => {
                    setShowQuickForm(null);
                    setFormData({});
                  }}
                  className="flex-1 px-3 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition font-medium text-sm"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        )}
        </div>
      )}
    </>
  );
}
